### PR TITLE
Feature/homework02 sandra

### PR DESCRIPTION
**Pull request by SandraMojsova**

### CODE REVIEW

**Review by emillija — APPROVED** [review]
Good job

**Review by dpeshevski — APPROVED** [review]

**Review by BojanaMR — APPROVED** [review]

**Review by ignat-ivanov — APPROVED** [review]

**Comment by dpeshevski** [comment]
Ti fali folder so outcomes, te molam dodadi gi.

**Review by dpeshevski — CHANGES_REQUESTED** [review]
Ti fali folder so outcomes, te molam dodadi gi.

**Comment by SandraMojsova** [comment]
Dodaden e folder so outcomes.

**Review by dpeshevski — APPROVED** [review]

**Pull request merged**
